@description('Azure region for all resources.')
param location string

@description('Azure region for API Management.')
param apimLocation string

@description('Deterministic token generated by the subscription-scoped entry point.')
param resourceToken string

@description('Deterministic token for the globally unique API Management service name.')
param apimResourceToken string

@description('Publisher email required by API Management.')
param publisherEmail string

@description('Publisher organization shown by API Management.')
param publisherName string

@description('Microsoft Entra object ID granted Monitoring Reader on Application Insights. Leave empty to skip the assignment.')
param telemetryReaderPrincipalId string = ''

@description('Deploy APIM into a VNet and disable public access to Azure OpenAI.')
param enablePrivateNetworking bool = false

@description('Resource ID of the dedicated APIM subnet.')
param apimSubnetResourceId string = ''

@description('Resource ID of the Azure OpenAI private endpoint subnet.')
param privateEndpointSubnetResourceId string = ''

@description('Resource ID of the VNet linked to the Azure OpenAI private DNS zone.')
param virtualNetworkResourceId string = ''

var azureOpenAIAccountName = 'azai${resourceToken}'
var azureOpenAIDeploymentName = 'azmdl${resourceToken}'
var managedIdentityName = 'azid${resourceToken}'
var apimServiceName = 'azapi${apimResourceToken}'
var apimApiId = 'azoa${resourceToken}'
var logAnalyticsName = 'azlog${resourceToken}'
var applicationInsightsName = 'azins${resourceToken}'
var privateEndpointName = 'azpe${resourceToken}'
var apimProductId = 'migration-${take(resourceToken, 12)}'
var apimSubscriptionId = 'migration-${take(resourceToken, 12)}'
var chatOperationId = 'azop${resourceToken}'
var operations = [
  {
    id: chatOperationId
    displayName: 'Chat completions'
    path: '/v1/chat/completions'
  }
  {
    id: 'responses'
    displayName: 'Responses'
    path: '/v1/responses'
  }
  {
    id: 'embeddings'
    displayName: 'Embeddings'
    path: '/v1/embeddings'
  }
  {
    id: 'image-generations'
    displayName: 'Image generations'
    path: '/v1/images/generations'
  }
  {
    id: 'audio-transcriptions'
    displayName: 'Audio transcriptions'
    path: '/v1/audio/transcriptions'
  }
  {
    id: 'files'
    displayName: 'Files'
    path: '/v1/files'
  }
  {
    id: 'batches'
    displayName: 'Batches'
    path: '/v1/batches'
  }
  {
    id: 'fine-tuning-jobs'
    displayName: 'Fine-tuning jobs'
    path: '/v1/fine_tuning/jobs'
  }
]
var cognitiveServicesUserRoleId = subscriptionResourceId(
  'Microsoft.Authorization/roleDefinitions',
  'a97b65f3-24c7-4388-baec-2e87135dc908'
)
var monitoringReaderRoleId = subscriptionResourceId(
  'Microsoft.Authorization/roleDefinitions',
  '43d0d8ad-25c7-4714-9337-8ba259a9fe05'
)

resource managedIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2023-01-31' = {
  name: managedIdentityName
  location: location
}

resource azureOpenAI 'Microsoft.CognitiveServices/accounts@2024-10-01' = {
  name: azureOpenAIAccountName
  location: location
  kind: 'OpenAI'
  sku: {
    name: 'S0'
  }
  properties: {
    customSubDomainName: azureOpenAIAccountName
    disableLocalAuth: true
    publicNetworkAccess: enablePrivateNetworking ? 'Disabled' : 'Enabled'
    networkAcls: {
      defaultAction: enablePrivateNetworking ? 'Deny' : 'Allow'
    }
  }
}

resource openAIPrivateEndpoint 'Microsoft.Network/privateEndpoints@2024-05-01' = if (enablePrivateNetworking) {
  name: privateEndpointName
  location: location
  properties: {
    subnet: {
      id: privateEndpointSubnetResourceId
    }
    privateLinkServiceConnections: [
      {
        name: 'azure-openai'
        properties: {
          privateLinkServiceId: azureOpenAI.id
          groupIds: [
            'account'
          ]
        }
      }
    ]
  }
}

resource openAIPrivateDnsZone 'Microsoft.Network/privateDnsZones@2024-06-01' = if (enablePrivateNetworking) {
  name: 'privatelink.openai.azure.com'
  location: 'global'
}

resource openAIVirtualNetworkLink 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = if (enablePrivateNetworking) {
  parent: openAIPrivateDnsZone
  name: 'openai-vnet-link'
  location: 'global'
  properties: {
    registrationEnabled: false
    virtualNetwork: {
      id: virtualNetworkResourceId
    }
  }
}

resource openAIPrivateDnsZoneGroup 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2024-05-01' = if (enablePrivateNetworking) {
  parent: openAIPrivateEndpoint
  name: 'default'
  properties: {
    privateDnsZoneConfigs: [
      {
        name: 'openai'
        properties: {
          privateDnsZoneId: openAIPrivateDnsZone.id
        }
      }
    ]
  }
}

resource modelDeployment 'Microsoft.CognitiveServices/accounts/deployments@2024-10-01' = {
  parent: azureOpenAI
  name: azureOpenAIDeploymentName
  sku: {
    name: 'GlobalStandard'
    capacity: 10
  }
  properties: {
    currentCapacity: 10
    model: {
      format: 'OpenAI'
      name: 'gpt-4.1-mini'
      version: '2025-04-14'
    }
    raiPolicyName: 'Microsoft.DefaultV2'
    versionUpgradeOption: 'OnceCurrentVersionExpired'
  }
}

resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: logAnalyticsName
  location: location
  properties: {
    retentionInDays: 30
  }
}

resource applicationInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: applicationInsightsName
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logAnalytics.id
  }
}

resource telemetryMonitoringReader 'Microsoft.Authorization/roleAssignments@2022-04-01' = if (!empty(telemetryReaderPrincipalId)) {
  name: guid(applicationInsights.id, telemetryReaderPrincipalId, monitoringReaderRoleId)
  scope: applicationInsights
  properties: {
    principalId: telemetryReaderPrincipalId
    principalType: 'User'
    roleDefinitionId: monitoringReaderRoleId
  }
}

resource apim 'Microsoft.ApiManagement/service@2024-05-01' = {
  name: apimServiceName
  location: apimLocation
  sku: {
    name: 'Developer'
    capacity: 1
  }
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${managedIdentity.id}': {}
    }
  }
  properties: {
    publisherEmail: publisherEmail
    publisherName: publisherName
    publicNetworkAccess: 'Enabled'
    virtualNetworkType: enablePrivateNetworking ? 'External' : 'None'
    ...(enablePrivateNetworking ? {
      virtualNetworkConfiguration: {
        subnetResourceId: apimSubnetResourceId
      }
    } : {})
    customProperties: {
      'Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls10': 'False'
      'Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Tls11': 'False'
    }
  }
}

resource apimApplicationInsightsLogger 'Microsoft.ApiManagement/service/loggers@2024-05-01' = {
  parent: apim
  name: 'migration-application-insights'
  properties: {
    loggerType: 'applicationInsights'
    credentials: {
      instrumentationKey: applicationInsights.properties.InstrumentationKey
    }
    isBuffered: true
    resourceId: applicationInsights.id
  }
}

resource cognitiveServicesUser 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(azureOpenAI.id, managedIdentity.id, cognitiveServicesUserRoleId)
  scope: azureOpenAI
  properties: {
    principalId: managedIdentity.properties.principalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: cognitiveServicesUserRoleId
  }
}

resource openAIAPI 'Microsoft.ApiManagement/service/apis@2024-05-01' = {
  parent: apim
  name: apimApiId
  properties: {
    apiType: 'http'
    displayName: 'OpenAI API v1'
    path: 'openai'
    protocols: [
      'https'
    ]
    serviceUrl: azureOpenAI.properties.endpoint
    subscriptionRequired: true
  }
}

resource openAIAPIDiagnostic 'Microsoft.ApiManagement/service/apis/diagnostics@2024-05-01' = {
  parent: openAIAPI
  name: 'applicationinsights'
  properties: {
    alwaysLog: 'allErrors'
    backend: {
      request: {
        body: {
          bytes: 0
        }
        headers: []
      }
      response: {
        body: {
          bytes: 0
        }
        headers: []
      }
    }
    frontend: {
      request: {
        body: {
          bytes: 0
        }
        headers: []
      }
      response: {
        body: {
          bytes: 0
        }
        headers: []
      }
    }
    httpCorrelationProtocol: 'W3C'
    logClientIp: false
    loggerId: apimApplicationInsightsLogger.id
    metrics: true
    sampling: {
      samplingType: 'fixed'
      percentage: 100
    }
    verbosity: 'information'
  }
}

resource openAIOperations 'Microsoft.ApiManagement/service/apis/operations@2024-05-01' = [for operation in operations: {
  parent: openAIAPI
  name: operation.id
  properties: {
    displayName: operation.displayName
    method: 'POST'
    urlTemplate: operation.path
    templateParameters: []
    responses: []
  }
}]

resource openAIOperationPolicies 'Microsoft.ApiManagement/service/apis/operations/policies@2024-05-01' = [for (operation, index) in operations: {
  parent: openAIOperations[index]
  name: 'policy'
  properties: {
    format: 'rawxml'
    value: operation.id == chatOperationId
      ? replace(
          replace(
            replace(
              replace(
                loadTextContent('../samples/apim-unified-chat-policy.xml'),
                '__APIM_IDENTITY_CLIENT_ID__',
                managedIdentity.properties.clientId
              ),
              '__DEPLOYMENT_NAME__',
              modelDeployment.name
            ),
            '__V1_BACKEND_URL__',
            azureOpenAI.properties.endpoint
          ),
          '__LEGACY_BACKEND_URL__',
          azureOpenAI.properties.endpoint
        )
      : replace(
          replace(
            loadTextContent('../samples/apim-policy.xml'),
            '__APIM_IDENTITY_CLIENT_ID__',
            managedIdentity.properties.clientId
          ),
          '__BACKEND_PATH__',
          '/openai${operation.path}'
        )
  }
  dependsOn: [
    cognitiveServicesUser
  ]
}]

resource migrationProduct 'Microsoft.ApiManagement/service/products@2024-05-01' = {
  parent: apim
  name: apimProductId
  properties: {
    displayName: 'OpenAI v1 migration'
    approvalRequired: false
    state: 'published'
    subscriptionRequired: true
  }
}

resource migrationProductApi 'Microsoft.ApiManagement/service/products/apis@2024-05-01' = {
  parent: migrationProduct
  name: openAIAPI.name
}

resource migrationSubscription 'Microsoft.ApiManagement/service/subscriptions@2024-05-01' = {
  parent: apim
  name: apimSubscriptionId
  properties: {
    allowTracing: false
    displayName: 'OpenAI v1 migration automation'
    scope: migrationProduct.id
    state: 'active'
  }
}

resource apimDiagnostics 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'send-to-log-analytics'
  scope: apim
  properties: {
    workspaceId: logAnalytics.id
    logs: [
      {
        categoryGroup: 'allLogs'
        enabled: true
      }
    ]
    metrics: [
      {
        category: 'AllMetrics'
        enabled: true
      }
    ]
  }
}

resource alertActionGroup 'Microsoft.Insights/actionGroups@2023-01-01' = {
  name: 'OpenAI migration alerts'
  location: 'global'
  properties: {
    enabled: true
    groupShortName: 'oaiv1'
    emailReceivers: [
      {
        name: 'APIM publisher'
        emailAddress: publisherEmail
        useCommonAlertSchema: true
      }
    ]
  }
}

resource failedRequestsAlert 'Microsoft.Insights/metricAlerts@2018-03-01' = {
  name: 'APIM OpenAI failed requests'
  location: 'global'
  properties: {
    description: 'More than five failed APIM requests in five minutes.'
    severity: 2
    enabled: true
    scopes: [
      apim.id
    ]
    evaluationFrequency: 'PT1M'
    windowSize: 'PT5M'
    criteria: {
      'odata.type': 'Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria'
      allOf: [
        {
          name: 'FailedRequests'
          metricNamespace: 'Microsoft.ApiManagement/service'
          metricName: 'FailedRequests'
          operator: 'GreaterThan'
          threshold: 5
          timeAggregation: 'Total'
          criterionType: 'StaticThresholdCriterion'
        }
      ]
    }
    actions: [
      {
        actionGroupId: alertActionGroup.id
      }
    ]
  }
}

output azureOpenAIAccountName string = azureOpenAI.name
output azureOpenAIBaseUrl string = '${azureOpenAI.properties.endpoint}openai/v1/'
output azureOpenAIDeploymentName string = modelDeployment.name
output apimServiceName string = apim.name
output apimApiId string = openAIAPI.name
output apimOpenAIBaseUrl string = '${apim.properties.gatewayUrl}/openai/v1/'
output apimSubscriptionId string = migrationSubscription.name
output applicationInsightsName string = applicationInsights.name
output logAnalyticsWorkspaceName string = logAnalytics.name
